resolver: lts-18.28
extra-deps:
- web-inv-route-0.1.3.1
- invertible-hxt-0.1
- git: https://github.com/dylex/invertible
  commit: fbeb1303e3decbcaa2502278dc2d85c57910c8d9 # 0.2.0.7
  subdirs:
  - conduit
- git: https://github.com/dylex/waimwork
  commit: 0ec1caed3aaa4583430484b2b63b5793b94cdb61
packages:
- rpc
- nfs
- webdav
flags:
  web-inv-route:
    snap: false
    happstack: false
  ONC-RPC:
    bindresvport: true
explicit-setup-deps:
  nfs: true
