resolver: lts-18.28
extra-deps:
- web-inv-route-0.1.3.2
- invertible-hxt-0.1
- git: https://github.com/dylex/invertible
  commit: e203c6a729fde87b1f903c3f468f739a085fb446
  subdirs:
  - conduit
- git: https://github.com/dylex/waimwork
  commit: 8ccaa63ac6b80a4ebc9ad7d61ca38cbb009e8f3c
packages:
- rpc
- nfs
- webdav
flags:
  web-inv-route:
    snap: false
    happstack: false
  ONC-RPC:
    bindresvport: true
explicit-setup-deps:
  nfs: true
